### PR TITLE
Gemspec now reflects dependencies required to run campfire_exporter

### PR DESCRIPTION
**Pull request by andrewwong1221**
I noticed that there were runtime dependencies missing when installing campfire_exporter for the first time.  This commit should resolve that issue.

### CODE REVIEW

**Comment by precipice** [comment]
I didn't know about that - hugely helpful. Thanks!

**Comment by andrewwong1221** [comment]
Not entirely sure I got this whole pull request/forking action thing down.  I only wanted my commit, but all of your commits got thrown into it too.

**Comment by precipice** [comment]
Yeah, normally you should do a new pull request in a new branch. No worries, I'll cherry-pick.

**Comment by precipice** [comment]
Merged, and a new gem (v0.2.1) pushed: https://rubygems.org/gems/campfire_export

Thanks again!

**Pull request closed without merging**
